# Generated by Django 4.2 on 2023-04-13 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guestbook', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbookmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guestbook_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guestbookmodel',
            name='author_nickname',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, related_name='guestbook_author_nickname', to=settings.AUTH_USER_MODEL),
        ),
    ]
