# Generated by Django 4.2 on 2023-04-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='nickname',
            field=models.CharField(default='너는 닉네임이 뭐야?', max_length=256),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='site_address',
            field=models.CharField(default='git, blog주소작성해줘', max_length=256),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='speech',
            field=models.CharField(default='하고싶은말 있으면 같이적어줘', max_length=256),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='tmi',
            field=models.CharField(default='너의 tmi를 작성해줘', max_length=256),
        ),
    ]
