# Generated by Django 4.2 on 2023-04-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usermodel_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='nickname',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='site_address',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='speech',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='tmi',
            field=models.CharField(default='', max_length=256),
        ),
    ]
